version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always

    ports:
      - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: 18lTdj5a3V5qTyEZ
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: pgDb
